[package]
name = "find-git"
version = "0.1.0"
authors = ["Reinier Maas <reinier.maas@channable.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "*"
git2 = "*"
